---
- name: be sure php is installed
  yum: name={{item}} state=installed enablerepo=epel
  with_items:
    - php
    - php-mysql
    - php-mbstring
    - php-gd
    - php-pear
    - php-pecl-apcu
  notify:
    - restart httpd
  tags: php

- name: copy info.php
  copy: src=roles/web-server/templates/info.php dest=/var/www/html
  tags: php

- name: set timezone in php.ini
  lineinfile: >
    dest=/etc/php.ini
    regexp='^;?date.timezone ='
    line='date.timezone = Asia/Tokyo'
    owner=root
    group=root
    mode=0644
  notify: restart httpd
  tags: php
